; Mental Omega (MO) CnCNet Client settings
; Control definitions have moved to GameLobbyBase.ini per client v2.12 architecture.

[General]
Sides=United States,Euro Alliance,Pacific Front,Russia,Confederation,China,PsiCorps,Scorpion Cell,Epsilon HQ,Haihead,Coronia,Last Bastion
StartingLocationAngularVelocity=0.01
ReservedStartingLocationAngularVelocity=0.01

[RandomSelectors]
Any Allies=0,1,2
Any Soviets=3,4,5
Any Epsilon=6,7,8
Any Foehn=9,10,11

; Multiplayer colors. Syntax: <Name>=R,G,B,<rulesmo [Colors] 0-based index>
[MPColors]
Teal=0,168,168,0
Red=255,0,0,1
Aqua=0,255,255,3
Green=1,255,0,4
Purple=180,91,229,5
Yellow=255,216,0,6
Blue=0,150,255,7
Orange=255,132,0,8
Magenta=223,0,255,9
Brown=178,103,50,10
Fern=119,190,38,11
Crimson=178,0,66,12
Sky=145,180,255,13
Pink=255,105,180,43
Jade=0,160,80,36
Lime=160,240,0,35
Neon=80,220,50,27
Gold=210,175,40,29
Tan=195,165,110,21

; Keys always written to spawn.ini at game start. Can be overridden by game mode code.
[ForcedSpawnIniOptions]
FogOfWar=No
MultiEngineer=Yes
ReconnectTimeout=1400
Protocol=0
FrameSendRate=2
