; Main Menu Settings

[ExtraPictureBoxes]

[MainMenu]
Size=1280,720

[MainMenuUIPanel]
Size=1280,720

; Buttons

[btnNewCampaign]
Size=145,42
Location=885,283
Text=Campaign
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnSkirmish]
Size=145,42
Location=885,325
Text=Skirmish
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnCnCNet]
Size=145,42
Location=885,367
Text=Online
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnLan]
Size=145,42
Location=885,409
Text=LAN
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnLoadGame]
Size=145,42
Location=885,451
Text=Load Game
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnOptions]
Size=145,42
;Location=885,451
Location=885,493
Text=Options
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnMapEditor]
Size=145,42
Location=885,535
Text=Map Editor
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnStatistics]
Size=145,42
;Visible=0
Location=885,577
Text=Statistics
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnExit]
Size=145,42
Location=885,619
Text=Quit Game
IdleTexture=MainMenu\button.png
HoverTexture=MainMenu\button_c.png
HoverSoundEffect=button.wav
FontIndex=1

[btnExtras]
Size=24,24
Location=1016,242
Visible=0

[btnCredits]
Size=192,35
Location=461,545
ForeColor=255,255,0
Font=Arial,Bold,9.25
;Text=Credits
Visible=0

; Labels

[lblUpdateStatus]
Location=249,661
ForeColor=255,255,0
BorderStyle=None
Font=Arial,Bold,9.25

[lblCnCNetStatus]
Location=495,92
ForeColor=45,255,0
Font=Arial,Bold,7.25
Text= ;blank  

[lblCnCNetPlayerCount]
Location=946,152
ForeColor=255,0,0
Font=Arial,Bold,7.25

[lblVersion]
Location=948,663
ForeColor=255,255,0
Font=Arial,Bold,9.25

[ExtraControls]
0=menu_fb:XNALinkButton
1=menu_yt:XNALinkButton
2=menu_tw:XNALinkButton
3=menu_dc:XNALinkButton
4=lblPlayersOnline:XNALabel

[menu_fb]
Location=501,579
IdleTexture=menu_fb.png
HoverTexture=menu_fb.png
Size=21,21
URL=https://facebook.com/MentalOmegaAPYR
Visible=0

[menu_yt]
Location=561,579
IdleTexture=menu_yt.png
HoverTexture=menu_yt.png
Size=21,21
URL=https://www.youtube.com/MentalOmegaAPYR
Visible=0

[menu_tw]
Location=531,579
IdleTexture=menu_tw.png
HoverTexture=menu_tw.png
Size=21,21
URL=https://twitter.com/speeder_mo
Visible=0

[menu_dc]
Location=591,579
IdleTexture=menu_dc.png
HoverTexture=menu_dc.png
Size=21,21
URL=https://discord.gg/KpJzhWY
Visible=0

[lblPlayersOnline]
Location=913,86;946,138
Text=Players Online
Font=Arial,Bold,7.25
ForeColor=255,0,0

;END