[General]
TeamDelays=2000,2500,3500 ;
AIVirtualPurifiers=4,2,0 ;
AIHateDelays=30,50,70 ;
MultiplayerAICM=400,0,0
;
FillEarliestTeamProbability=100,100,100
MinimumAIDefensiveTeams=1,1,1
MaximumAIDefensiveTeams=2,2,2
TotalAITeamCap=70,50,30
;
AlliedBaseDefenseCounts=25,20,6
SovietBaseDefenseCounts=25,22,6
ThirdBaseDefenseCounts=25,22,6

[FourthSide]
AI.BaseDefenseCounts=25,22,6

;DISABLE ANNOYING ASS SPECIALS
;Allies
[MercurySpecial]
SW.AITargeting=None

[HunterSeekerSpecial]
SW.AITargeting=None

[BlackWidowSpecial]
SW.AITargeting=None

[BlackWidowAlphaSpecial]
SW.AITargeting=None

;Soviets
[RadAttackSpecial]
SW.AITargeting=None

[PackAttackSpecial]
SW.AITargeting=None

[MotorAmbushSpecial]
SW.AITargeting=None

[FlameTowerSpecial]
SW.AITargeting=None

[WallbusterSpecial]
SW.AITargeting=None

;Epsilon
[RisenMonolithSpecial]
SW.AITargeting=None

[TickTrapSpawn]
SW.AITargeting=None

[ToxicStrikeSpecial]
SW.AITargeting=None

[MutationSpecial]
SW.AITargeting=None

;Foehn
[ChaosTouchSpecial]
SW.AITargeting=None

[BlackoutMissileSpecial]
SW.AITargeting=None

[DevourerSpecial]
SW.AITargeting=None

[FAHARB]
AIBuildThis=no

[FABOID]
AIBuildThis=no

[GATECH]
Spyable=yes

[NATECHR]
Spyable=yes

[NATECHC]
Spyable=yes

[NATEK]
Spyable=yes

[YATECH]
Spyable=yes

[YATXCH]
Spyable=yes

[FACLDP]
Spyable=yes

[GACNST]
Spyable=yes

[NACNST]
Spyable=yes

[YACNST]
Spyable=yes

[YACXST]
Spyable=yes

[FACNST]
Spyable=yes

;Enable Stolen Tech

[QUICK]
Prerequisite=ALLWEAP,GATECH,ALLT2
Prerequisite.StolenTechs=1,11
Owner=Europeans,UnitedStates,Pacific

[LIONH]
Prerequisite=GAAIRC,GATECH,ALLT2
Prerequisite.StolenTechs=2,12
Owner=Europeans,UnitedStates,Pacific

[CHRP]
Prerequisite=ALLWEAP,GATECH,ALLT2
Prerequisite.StolenTechs=3,13
Owner=Europeans,UnitedStates,Pacific

[AHVYBOT2]
Prerequisite=ALLWEAP,GATECH,ALLT2
Prerequisite.StolenTechs=4,14
Owner=Europeans,UnitedStates,Pacific

[GRUMBLE]
Prerequisite=SOVWEAP,SOVTECH
Prerequisite.StolenTechs=1,11
Owner=USSR,Latin,Chinese

[MAMM]
Prerequisite=SOVWEAP,SOVTECH
Prerequisite.StolenTechs=2,12
Owner=USSR,Latin,Chinese

[SYCKLE]
Prerequisite=SOVWEAP,SOVTECH
Prerequisite.StolenTechs=3,13
Owner=USSR,Latin,Chinese

[IDRAG]
Prerequisite=SOVWEAP,SOVTECH
Prerequisite.StolenTechs=4,14
Owner=USSR,Latin,Chinese

[TRACTOR]
Prerequisite=YURWEAP,ANYPLUG
Prerequisite.StolenTechs=1,11
Owner=PsiCorps,Headquaters,ScorpionCell

[WORMQ]
Prerequisite=YURWEAP,ANYPLUG
Prerequisite.StolenTechs=2,12
Owner=PsiCorps,Headquaters,ScorpionCell

[SEIZER]
Prerequisite=YAAIRF,ANYPLUG
Prerequisite.StolenTechs=3,13
Owner=PsiCorps,Headquaters,ScorpionCell

[SALA]
Prerequisite=YURWEAP,ANYPLUG
Prerequisite.StolenTechs=4,14
Owner=PsiCorps,Headquaters,ScorpionCell

[PHNT]
Prerequisite=FOEWEAP,FOETECH
Prerequisite.StolenTechs=1,11
Owner=Guild1,Guild2,Guild3

[SEITAAD]
Prerequisite=FOEWEAP,FOETECH
Prerequisite.StolenTechs=2,12
Owner=Guild1,Guild2,Guild3

[ARCH]
Prerequisite=FOEWEAP,FOETECH
Prerequisite.StolenTechs=3,13
Owner=Guild1,Guild2,Guild3

[RAMW]
Prerequisite=FOEWEAP,FOETECH
Prerequisite.StolenTechs=4,14
Owner=Guild1,Guild2,Guild3

[CYCOM]
Prerequisite=ALLRAX,SOVRAX,YURRAX,FOERAX,TECH
Prerequisite.StolenTechs=1,2,3,4
Owner=USSR,Latin,Chinese,PsiCorps,Headquaters,ScorpionCell,Europeans,UnitedStates,Pacific,Guild1,Guild2,Guild3

;TechBuild
[CAAIRP]
BaseNormal=yes

[CASTRF]
BaseNormal=yes

[CASHLD]
BaseNormal=yes

[CATPAD]
BaseNormal=yes

[CAACAD]
BaseNormal=yes

[CADEFB]
BaseNormal=yes

[CAHMCH]
BaseNormal=yes

[CAAERO]
BaseNormal=yes

[CADOCK]
BaseNormal=yes

[CAMISL]
BaseNormal=yes

[CAREFN]
BaseNormal=yes

[CACOMN]
BaseNormal=yes

[CAOILD]
BaseNormal=yes

[CABANK]
BaseNormal=yes

[CAPOWR]
BaseNormal=yes

[CANRCT]
BaseNormal=yes

[CAMACH]
BaseNormal=yes

[CATHOSP]
BaseNormal=yes

[CAFHOSP]
BaseNormal=yes

[CASLAB]
BaseNormal=yes

;reveal
[GACSPH]
RevealToAll=yes

[NAPSYB]
RevealToAll=yes

[GAWEAT]
RevealToAll=yes

[NAIRON]
RevealToAll=yes

[NAMISL]
RevealToAll=yes

[YAGNTC]
RevealToAll=yes

[YAPPET]
RevealToAll=yes

[YAPPXT]
RevealToAll=yes

[FABLST]
RevealToAll=yes

[FAHARB]
RevealToAll=yes

[FAELEV]
RevealToAll=yes

[NAPSYB]
RevealToAll=yes